#include <stdio.h>
#include <stdlib.h>
#include <string.h>

FILE *outfile;

#define SECTION1 \
"/* This file was autogenerated by symgen. See symgen.c */\n" \
"/* By default the enum elements are sourced from symbols.def */\n" \
"\n" \
"enum Symbol {\n" \
"\tNULL_SYMBOL,\n"

void genEnumLine(const char* word){
	fprintf(outfile, "\t%s,\n", word);
}

#define SECTION2 \
"\tUNKNOWN_SYMBOL,\n" \
"\tEND_OF_SYMBOLS_SYMBOL\n" \
"};\n" \
"\n" \
"const char * stringifySymbol(enum Symbol sym);\n" \
"enum Symbol parseSymbol(const char *string);\n"

#define SECTION3 \
"/* This file was autogenerated by symgen. See symgen.c */\n" \
"/* By default the enum elements are sourced from symbols.def */\n" \
"\n" \
"#include <string.h>\n" \
"#include <symbols.h>\n" \
"\n" \
"const char * stringifySymbol(enum Symbol sym){\n" \
"\tswitch(sym){\n" \
"\t\tcase NULL_SYMBOL: return \"NULL_SYMBOL\";\n"

void genStringifyLine(const char *word){
	fprintf(outfile, "\t\tcase %s: return \"%s\";\n", word, word);
}

#define SECTION4 \
"\t\tdefault: return \"UNKNOWN_SYMBOL\";\n" \
"\t}\n" \
"}\n" \
"\n" \
"enum Symbol parseSymbol(const char* s){\n" \
"\tif(strcmp(s, \"NULL_SYMBOL\") == 0) return NULL_SYMBOL;\n"

void genParseLine(const char *word){
	fprintf(outfile, "\telse if(strcmp(s, \"%s\") == 0) return %s;\n", word, word);
}

#define SECTION5 \
"\telse return UNKNOWN_SYMBOL;\n" \
"}\n"


void eachSymbol(const char* path, void (*eat)(const char* word)){
	FILE *symfile = fopen(path, "r"); if(symfile == NULL){ puts("symgen 💣"); exit(1); }
	for(int i = 0; i < 10000; i++){
		char word[64];
		int c = fscanf(symfile, "%63s\n", word);
		if(c == EOF && ferror(symfile)){ puts("symgen 💣💣"); exit(1); }
		if(c == EOF){ fclose(symfile); return; }
		eat(word);
	}

	puts("symgen 💣💣💣");
	exit(1);
}

int main(int argc, char **argv){
	char sympath[1024] = "symbols.def";
	char outpathH[1024] = "symbols.h";
	char outpathC[1024] = "symbols.c";

	if(argc > 1){ strncpy(sympath, argv[1], 1024); sympath[1023] = '\0'; }

	outfile = fopen(outpathH, "w"); if(outfile == NULL){ printf("symgen can't open output file %s", outpathH); exit(1); }

	fputs(SECTION1, outfile);
	eachSymbol(sympath, genEnumLine);
	fputs(SECTION2, outfile);

	fclose(outfile);

	outfile = fopen(outpathC, "w"); if(outfile == NULL){ printf("symgen can't open output file %s", outpathC); exit(1); }

	fputs(SECTION3, outfile);
	eachSymbol(sympath, genStringifyLine);
	fputs(SECTION4, outfile);
	eachSymbol(sympath, genParseLine);
	fputs(SECTION5, outfile);

	return 0;
}
